# Use the latest Ubuntu image
FROM ubuntu:latest

# Update apt and upgrade installed software
RUN apt-get update && apt-get upgrade -y

# When the container runs, print “Hello, World!”
CMD ["echo", "Hello, World!"]
